# -*- coding: utf-8 -*-
"""house rent.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14r3UasShkVbyKWFLH9WkpFpyIIIbVIsE
"""

import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.io as pio
import numpy as np

df = pd.read_csv('House_Rent_Dataset.csv')

df.head

df.tail()

df.describe()

df2 = df.drop('Bathroom', axis =1)

df2.head()

df3 = df[['Rent', 'Size', 'City']]

df3.head()

plt.hist(x=df ['Rent'], color = 'green')

grafico = px. scatter_matrix(df, dimensions=['Area Locality', 'Rent'], color = 'Rent')
grafico.show()

grafico = px. scatter_matrix(df, dimensions=['Area Locality', 'Size'], color = 'Rent')
grafico.show()

df.plot ()

fig, ax = plt.subplots() 
ax.plot(['Rent'], [ "Area Locality"]);

size_df = df['Size'].value_counts()
size_df

fig = px.bar(size_df, x=size_df.index, y=size_df.values, color=size_df.index, 
       title='Valor de aluguel de acordo com o tamanho do imóvel', text=size_df.values)
fig.update_traces(width=50)
fig.update_layout(
    xaxis_title="Rent",
    yaxis_title="Size",
    font = dict(size=17))
fig.show()

fig = px.bar(df, x= 'City', y= 'Rent', color ='Area Locality', 
    #size_df, x=size_df.index, y=size_df.values, color=size_df.index, 
       title=('Valor de aluguel de acordo com a Cidade')
fig.update_traces(width=100)
fig.update_layout(
    xaxis_title="Rent",
    yaxis_title="City",
    font = dict(size=17))
fig.show()

fig = px.scatter(df, x='Size', y='Rent', color='BHK', size='Size', hover_data=['Rent'])
fig.update_layout(title='Valor do Aluguel de Acordo com o Tamanho do Imóvel ',
                  yaxis_zeroline=False, xaxis_zeroline=False)
fig.show()

plt.plot(df3['City'], df3['Rent'])

px.line(df3, x= 'City', y= 'Rent')

px.line(df3, x= 'City', y= 'Rent', color= 'Rent')

plt.plot(df3['Rent'], df3['Size'])

px.line(df3, x= 'Rent', y= 'Size')

px.line(df3, x= 'Rent', y= 'Size', color= 'Size')

df_munbai= df3[df3['City'] =='Munbai']

plt.plot(df["Area Locality"], ['Size'])

